services:
  browser-api:
    build: .
    ports:
      - "9081:8000"
    environment:
      - LLM=${LLM}
    volumes:
      - /dev/shm:/dev/shm # For Chrome memory efficiency
      - ./models:/models
